name: Integration tests
on:
  schedule:
    - cron: 0 0 1,8,15,22 * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
      - run: npm install
      - run: npm run build
      - run: npm run test:integration
        env:
          FIXER_API_KEY: ${{ secrets.FIXER_API_KEY }}
